In [54]:
import numpy as np
def func(A, k, i):

  #slicing

#Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )


#Trocando a coluna
  iChange = indexMax + i

  aux = np.copy( A[ k, : ] )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )


  return A



def applyGaussElimination( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            A = func(A, k, i)
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero 
            A[ i, k ] = 0
        
    return A, b

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


b=np.array([5, 6, 7, 15])

A = Aarr
print(A)


n = 3


x, y=applyGaussElimination( A, b, n )
print(x)



[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]


In [67]:
import numpy as np

def applyGaussElimination(A, b, n): 
    
    if (np.linalg.det(A)!=0):
        for k in np.arange( 0, n ): 
            if (A[k][k]==0):
                print('Erro! Pivo 0')
                return
            if (A[k+1][k]==0):
                continue
            else: 
                for i in np.arange( k + 1, n + 1 ): 
                    m = A[i, k] / A[k, k]
                    A[ i, k ] = 0
                    for j in np.arange(k + 1, n + 1):
                        A[i, j] -= m * A[k, j]
                        b[i] -= m * b[k] 

        return A, b
    else:
        print('Erro')
        return


A  = np.array([[3., 2., 4.], [1., 1., 2.], [4., 3., -2.] ])
b = np.array( [ 1., 2., 3. ] )
print('A \n', A)
print('b ', b, '\n\n')


n = np.shape(A)[0] - 1


C, d = applyGaussElimination(A, b, n)

print(C)
print(d)

A 
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
b  [1. 2. 3.] 


[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
[ 1.          1.33333333 -1.        ]


In [70]:
X  = np.array([[2., 1., -1.], [-3., -1., 2.], [-2., 1., 2.] ])
y = np.array( [ 8., -11., 3. ] )
print('A \n', X)
print('b ', y, '\n\n')


n = np.shape(A)[0] - 1


Z, w = applyGaussElimination(X, y, n)

print(Z)
print()
print('A matriz foi transformada em triangular superior, mas teriamos como simplificar ainda mais e encontrar a solução mais facilmente. Porém, o algoritmo não faz essa operação, finalizando quando a matriz está em forma de triangular superior.')

A 
 [[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
b  [  8. -11.   3.] 


[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]

A matriz foi transformada em triangular superior, mas teriamos como simplificar ainda mais e encontrar a solução mais facilmente. Porém, o algoritmo não faz essa operação, finalizando quando a matriz está em forma de triangular superior.
