In [5]:
import numpy as np


def func(A, k, i):

  #slicing

#Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )


#Trocando a coluna
  iChange = indexMax + i

  aux = np.copy( A[ k, : ] )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )


  return A



def applyGaussElimination( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            A = func(A, k, i)
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero 
            A[ i, k ] = 0
        
    return A, b

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


b=np.array([5, 6, 7, 15])

A = Aarr
print(A)


n = 3


x, y=applyGaussElimination( A, b, n )
print(x)



[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
